CREATE TABLE MUSTERI(
    MusteriID NUMBER GENERATED ALWAYS AS IDENTITY START WITH 1 PRIMARY KEY,
    MusteriAd VARCHAR(50),
    MusteriSoyad VARCHAR(50),
    MusteriCinsiyet VARCHAR(50),
    MusteriTC VARCHAR(50),
    MusteriKad VARCHAR(50),
    Musterisifre VARCHAR(50),
    MusteriOda VARCHAR(50),
    girisTarihi VARCHAR(50),
    cikisTarihi VARCHAR(50)
);
---INSERT INTO MUSTERI (MusteriAd,MusteriSoyad,MusteriCinsiyet,MusteriTC,MusteriKad,Musterisifre,MusteriOda,girisTarihi,cikisTarihi) VALUES ('furkan','ceylan','Erkek','127313','furkan','123','1','','');

CREATE TABLE ODALAR(
    OdaID NUMBER GENERATED ALWAYS AS IDENTITY START WITH 1 PRIMARY KEY,
    OdaAdi VARCHAR(100),
    OdaSahibi VARCHAR(100),
    OdaDurumu VARCHAR(100),
    buttonName VARCHAR(100)
);
CREATE TABLE YONETICI(
    YoneticiID NUMBER GENERATED ALWAYS AS IDENTITY START WITH 1 PRIMARY KEY,
    YoneticiKad VARCHAR(50),
    Yoneticisifre VARCHAR(50),
);
---INSERT INTO YONETICI (YoneticiKad,Yoneticisifre) VALUES ('yonetici','123');

--- SÝLMEDEN ÖNCEE ODAYI VE SAHÝBÝNÝ YEDEKLEME
CREATE OR REPLACE TRIGGER ODA_YEDEKLE
 BEFORE DELETE ON ODA.ODA_ODALAR
 FOR EACH ROW
 BEGIN
 INSERT INTO ODA.ODA_ODALAR
VALUES(:OLD.ODA_CLS_ID, :OLD.ODA_CLS_AD, :OLD.ODA_CLS_SOYAD,
:OLD.ODA_CLS_TC, :OLD.ODA_ODA_ODADURUMU);
END;
--- MÜÞTERÝ ID INCREEMENT
CREATE OR REPLACE TRIGGER ODA.MUS_ID_INC
BEFORE INSERT ON ODA.ODA_MUSTERI
FOR EACH ROW
BEGIN
 SELECT ID_INC.NEXTVAL
 INTO :NEW.ODA_MST_ID
 FROM DUAL;
END;



create or replace NONEDITIONABLE PROCEDURE YONETICIGIRIS
(
NICKNAME IN yonetýcý.yonetýcýkad%TYPE,
PASS IN yonetýcý.yonetýcýsýfre%TYPE,
DONUS OUT varchar2) AS

kuladi varchar2(50);
sif varchar2(50);

BEGIN
SELECT YONETICI.YoneticiKad,YONETICI.Yoneticisifre INTO kuladi,sif FROM YONETICI WHERE YONETICI.YoneticiKad=NICKNAME AND YONETICI.Yoneticisifre=PASS;
IF (NICKNAME=kuladi AND PASS=sif) THEN 
DONUS:='Giriþ Baþarýlý';
END IF;
EXCEPTION
WHEN OTHERS THEN
DONUS:='Giriþ Baþarýsýz';
END;



